package com.ipn.mx.model.dto;
// Generated 29/09/2019 12:36:04 AM by Hibernate Tools 4.3.1



/**
 * Becario generated by hbm2java
 */
public class Becario  implements java.io.Serializable {


     private String curp;
     private Direccion direccion;
     private Discapacidades discapacidades;
     private Gradoestudios gradoestudios;
     private Usuario usuario;
     private String nombreBecario;
     private String paternoBecario;
     private String maternoBecario;
     private int edad;
     private String numeroSeguridadSocial;
     private String telefono;
     private String celular;
     private boolean certificado;

    public Becario() {
    }

	
    public Becario(String curp, Gradoestudios gradoestudios, Usuario usuario, String nombreBecario, String paternoBecario, String maternoBecario, int edad, String telefono, boolean certificado) {
        this.curp = curp;
        this.gradoestudios = gradoestudios;
        this.usuario = usuario;
        this.nombreBecario = nombreBecario;
        this.paternoBecario = paternoBecario;
        this.maternoBecario = maternoBecario;
        this.edad = edad;
        this.telefono = telefono;
        this.certificado = certificado;
    }
    public Becario(String curp, Direccion direccion, Discapacidades discapacidades, Gradoestudios gradoestudios, Usuario usuario, String nombreBecario, String paternoBecario, String maternoBecario, int edad, String numeroSeguridadSocial, String telefono, String celular, boolean certificado) {
       this.curp = curp;
       this.direccion = direccion;
       this.discapacidades = discapacidades;
       this.gradoestudios = gradoestudios;
       this.usuario = usuario;
       this.nombreBecario = nombreBecario;
       this.paternoBecario = paternoBecario;
       this.maternoBecario = maternoBecario;
       this.edad = edad;
       this.numeroSeguridadSocial = numeroSeguridadSocial;
       this.telefono = telefono;
       this.celular = celular;
       this.certificado = certificado;
    }
   
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public Discapacidades getDiscapacidades() {
        return this.discapacidades;
    }
    
    public void setDiscapacidades(Discapacidades discapacidades) {
        this.discapacidades = discapacidades;
    }
    public Gradoestudios getGradoestudios() {
        return this.gradoestudios;
    }
    
    public void setGradoestudios(Gradoestudios gradoestudios) {
        this.gradoestudios = gradoestudios;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreBecario() {
        return this.nombreBecario;
    }
    
    public void setNombreBecario(String nombreBecario) {
        this.nombreBecario = nombreBecario;
    }
    public String getPaternoBecario() {
        return this.paternoBecario;
    }
    
    public void setPaternoBecario(String paternoBecario) {
        this.paternoBecario = paternoBecario;
    }
    public String getMaternoBecario() {
        return this.maternoBecario;
    }
    
    public void setMaternoBecario(String maternoBecario) {
        this.maternoBecario = maternoBecario;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getNumeroSeguridadSocial() {
        return this.numeroSeguridadSocial;
    }
    
    public void setNumeroSeguridadSocial(String numeroSeguridadSocial) {
        this.numeroSeguridadSocial = numeroSeguridadSocial;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public boolean isCertificado() {
        return this.certificado;
    }
    
    public void setCertificado(boolean certificado) {
        this.certificado = certificado;
    }




}


