package com.ipn.mx.model.dto;
// Generated 29/09/2019 12:36:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer idDireccion;
     private String calle;
     private String numeroExterior;
     private String numeroInterior;
     private String colonia;
     private String municipioDelegacion;
     private String entidadFederal;
     private String codigoPostal;
     private Set becarios = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Direccion() {
    }

	
    public Direccion(String calle, String numeroExterior, String colonia, String municipioDelegacion, String entidadFederal, String codigoPostal) {
        this.calle = calle;
        this.numeroExterior = numeroExterior;
        this.colonia = colonia;
        this.municipioDelegacion = municipioDelegacion;
        this.entidadFederal = entidadFederal;
        this.codigoPostal = codigoPostal;
    }
    public Direccion(String calle, String numeroExterior, String numeroInterior, String colonia, String municipioDelegacion, String entidadFederal, String codigoPostal, Set becarios, Set empresas) {
       this.calle = calle;
       this.numeroExterior = numeroExterior;
       this.numeroInterior = numeroInterior;
       this.colonia = colonia;
       this.municipioDelegacion = municipioDelegacion;
       this.entidadFederal = entidadFederal;
       this.codigoPostal = codigoPostal;
       this.becarios = becarios;
       this.empresas = empresas;
    }
   
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumeroExterior() {
        return this.numeroExterior;
    }
    
    public void setNumeroExterior(String numeroExterior) {
        this.numeroExterior = numeroExterior;
    }
    public String getNumeroInterior() {
        return this.numeroInterior;
    }
    
    public void setNumeroInterior(String numeroInterior) {
        this.numeroInterior = numeroInterior;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getMunicipioDelegacion() {
        return this.municipioDelegacion;
    }
    
    public void setMunicipioDelegacion(String municipioDelegacion) {
        this.municipioDelegacion = municipioDelegacion;
    }
    public String getEntidadFederal() {
        return this.entidadFederal;
    }
    
    public void setEntidadFederal(String entidadFederal) {
        this.entidadFederal = entidadFederal;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Set getBecarios() {
        return this.becarios;
    }
    
    public void setBecarios(Set becarios) {
        this.becarios = becarios;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


