package com.ipn.mx.model.dto;
// Generated 29/09/2019 12:36:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Discapacidades generated by hbm2java
 */
public class Discapacidades  implements java.io.Serializable {


     private Integer idDiscapacidad;
     private String nombreDiscapacidad;
     private String descripcionDiscapacidad;
     private Set becarios = new HashSet(0);

    public Discapacidades() {
    }

	
    public Discapacidades(String nombreDiscapacidad) {
        this.nombreDiscapacidad = nombreDiscapacidad;
    }
    public Discapacidades(String nombreDiscapacidad, String descripcionDiscapacidad, Set becarios) {
       this.nombreDiscapacidad = nombreDiscapacidad;
       this.descripcionDiscapacidad = descripcionDiscapacidad;
       this.becarios = becarios;
    }
   
    public Integer getIdDiscapacidad() {
        return this.idDiscapacidad;
    }
    
    public void setIdDiscapacidad(Integer idDiscapacidad) {
        this.idDiscapacidad = idDiscapacidad;
    }
    public String getNombreDiscapacidad() {
        return this.nombreDiscapacidad;
    }
    
    public void setNombreDiscapacidad(String nombreDiscapacidad) {
        this.nombreDiscapacidad = nombreDiscapacidad;
    }
    public String getDescripcionDiscapacidad() {
        return this.descripcionDiscapacidad;
    }
    
    public void setDescripcionDiscapacidad(String descripcionDiscapacidad) {
        this.descripcionDiscapacidad = descripcionDiscapacidad;
    }
    public Set getBecarios() {
        return this.becarios;
    }
    
    public void setBecarios(Set becarios) {
        this.becarios = becarios;
    }




}


