package com.ipn.mx.model.dto;
// Generated 29/09/2019 12:36:04 AM by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String rfc;
     private Direccion direccion;
     private Giroempresarial giroempresarial;
     private Responsableempresa responsableempresa;
     private Tipoempresa tipoempresa;
     private Usuario usuario;
     private String nombreEmpresa;
     private String telefono;
     private int numeroEmpleados;
     private int numeroBecariosAcapacitar;
     private Integer numeroBecariosCapacitando;
     private Integer numeroBecariosCapacitados;

    public Empresa() {
    }

	
    public Empresa(String rfc, Giroempresarial giroempresarial, Tipoempresa tipoempresa, Usuario usuario, String nombreEmpresa, String telefono, int numeroEmpleados, int numeroBecariosAcapacitar) {
        this.rfc = rfc;
        this.giroempresarial = giroempresarial;
        this.tipoempresa = tipoempresa;
        this.usuario = usuario;
        this.nombreEmpresa = nombreEmpresa;
        this.telefono = telefono;
        this.numeroEmpleados = numeroEmpleados;
        this.numeroBecariosAcapacitar = numeroBecariosAcapacitar;
    }
    public Empresa(String rfc, Direccion direccion, Giroempresarial giroempresarial, Responsableempresa responsableempresa, Tipoempresa tipoempresa, Usuario usuario, String nombreEmpresa, String telefono, int numeroEmpleados, int numeroBecariosAcapacitar, Integer numeroBecariosCapacitando, Integer numeroBecariosCapacitados) {
       this.rfc = rfc;
       this.direccion = direccion;
       this.giroempresarial = giroempresarial;
       this.responsableempresa = responsableempresa;
       this.tipoempresa = tipoempresa;
       this.usuario = usuario;
       this.nombreEmpresa = nombreEmpresa;
       this.telefono = telefono;
       this.numeroEmpleados = numeroEmpleados;
       this.numeroBecariosAcapacitar = numeroBecariosAcapacitar;
       this.numeroBecariosCapacitando = numeroBecariosCapacitando;
       this.numeroBecariosCapacitados = numeroBecariosCapacitados;
    }
   
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public Giroempresarial getGiroempresarial() {
        return this.giroempresarial;
    }
    
    public void setGiroempresarial(Giroempresarial giroempresarial) {
        this.giroempresarial = giroempresarial;
    }
    public Responsableempresa getResponsableempresa() {
        return this.responsableempresa;
    }
    
    public void setResponsableempresa(Responsableempresa responsableempresa) {
        this.responsableempresa = responsableempresa;
    }
    public Tipoempresa getTipoempresa() {
        return this.tipoempresa;
    }
    
    public void setTipoempresa(Tipoempresa tipoempresa) {
        this.tipoempresa = tipoempresa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getNumeroEmpleados() {
        return this.numeroEmpleados;
    }
    
    public void setNumeroEmpleados(int numeroEmpleados) {
        this.numeroEmpleados = numeroEmpleados;
    }
    public int getNumeroBecariosAcapacitar() {
        return this.numeroBecariosAcapacitar;
    }
    
    public void setNumeroBecariosAcapacitar(int numeroBecariosAcapacitar) {
        this.numeroBecariosAcapacitar = numeroBecariosAcapacitar;
    }
    public Integer getNumeroBecariosCapacitando() {
        return this.numeroBecariosCapacitando;
    }
    
    public void setNumeroBecariosCapacitando(Integer numeroBecariosCapacitando) {
        this.numeroBecariosCapacitando = numeroBecariosCapacitando;
    }
    public Integer getNumeroBecariosCapacitados() {
        return this.numeroBecariosCapacitados;
    }
    
    public void setNumeroBecariosCapacitados(Integer numeroBecariosCapacitados) {
        this.numeroBecariosCapacitados = numeroBecariosCapacitados;
    }




}


