package com.ipn.mx.model.dto;
// Generated 29/09/2019 12:36:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Responsableempresa generated by hbm2java
 */
public class Responsableempresa  implements java.io.Serializable {


     private Integer idResponsableEmpresa;
     private String nombreResponsable;
     private String paternoResponsable;
     private String maternoResponsable;
     private String cargo;
     private String telefono;
     private String celular;
     private Set empresas = new HashSet(0);

    public Responsableempresa() {
    }

	
    public Responsableempresa(String nombreResponsable, String paternoResponsable, String maternoResponsable, String cargo, String telefono) {
        this.nombreResponsable = nombreResponsable;
        this.paternoResponsable = paternoResponsable;
        this.maternoResponsable = maternoResponsable;
        this.cargo = cargo;
        this.telefono = telefono;
    }
    public Responsableempresa(String nombreResponsable, String paternoResponsable, String maternoResponsable, String cargo, String telefono, String celular, Set empresas) {
       this.nombreResponsable = nombreResponsable;
       this.paternoResponsable = paternoResponsable;
       this.maternoResponsable = maternoResponsable;
       this.cargo = cargo;
       this.telefono = telefono;
       this.celular = celular;
       this.empresas = empresas;
    }
   
    public Integer getIdResponsableEmpresa() {
        return this.idResponsableEmpresa;
    }
    
    public void setIdResponsableEmpresa(Integer idResponsableEmpresa) {
        this.idResponsableEmpresa = idResponsableEmpresa;
    }
    public String getNombreResponsable() {
        return this.nombreResponsable;
    }
    
    public void setNombreResponsable(String nombreResponsable) {
        this.nombreResponsable = nombreResponsable;
    }
    public String getPaternoResponsable() {
        return this.paternoResponsable;
    }
    
    public void setPaternoResponsable(String paternoResponsable) {
        this.paternoResponsable = paternoResponsable;
    }
    public String getMaternoResponsable() {
        return this.maternoResponsable;
    }
    
    public void setMaternoResponsable(String maternoResponsable) {
        this.maternoResponsable = maternoResponsable;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


