package com.ipn.mx.model.dto;
// Generated 29/09/2019 12:36:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoempresa generated by hbm2java
 */
public class Tipoempresa  implements java.io.Serializable {


     private Integer idTipoEmpresa;
     private String nombreTipoEmpresa;
     private String descripcionTipoEmpresa;
     private Set empresas = new HashSet(0);

    public Tipoempresa() {
    }

	
    public Tipoempresa(String nombreTipoEmpresa) {
        this.nombreTipoEmpresa = nombreTipoEmpresa;
    }
    public Tipoempresa(String nombreTipoEmpresa, String descripcionTipoEmpresa, Set empresas) {
       this.nombreTipoEmpresa = nombreTipoEmpresa;
       this.descripcionTipoEmpresa = descripcionTipoEmpresa;
       this.empresas = empresas;
    }
   
    public Integer getIdTipoEmpresa() {
        return this.idTipoEmpresa;
    }
    
    public void setIdTipoEmpresa(Integer idTipoEmpresa) {
        this.idTipoEmpresa = idTipoEmpresa;
    }
    public String getNombreTipoEmpresa() {
        return this.nombreTipoEmpresa;
    }
    
    public void setNombreTipoEmpresa(String nombreTipoEmpresa) {
        this.nombreTipoEmpresa = nombreTipoEmpresa;
    }
    public String getDescripcionTipoEmpresa() {
        return this.descripcionTipoEmpresa;
    }
    
    public void setDescripcionTipoEmpresa(String descripcionTipoEmpresa) {
        this.descripcionTipoEmpresa = descripcionTipoEmpresa;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


