package com.ipn.mx.model.dto;
// Generated 29/09/2019 12:36:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String correo;
     private int idRolUsuario;
     private String contrasena;
     private Set empresas = new HashSet(0);
     private Set becarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String correo, int idRolUsuario, String contrasena) {
        this.correo = correo;
        this.idRolUsuario = idRolUsuario;
        this.contrasena = contrasena;
    }
    public Usuario(String correo, int idRolUsuario, String contrasena, Set empresas, Set becarios) {
       this.correo = correo;
       this.idRolUsuario = idRolUsuario;
       this.contrasena = contrasena;
       this.empresas = empresas;
       this.becarios = becarios;
    }
    
    public Usuario(String correo){
        this.correo = correo;
    }
    
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public int getIdRolUsuario() {
        return this.idRolUsuario;
    }
    
    public void setIdRolUsuario(int idRolUsuario) {
        this.idRolUsuario = idRolUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }
    public Set getBecarios() {
        return this.becarios;
    }
    
    public void setBecarios(Set becarios) {
        this.becarios = becarios;
    }




}


